### ISSUE TITLE
Error on initialisation

### ISSUE THREAD

**Issue by turiphro** [lamby/django-slack#17]
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/home/ttn-dev/.venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django_slack/__init__.py", line 244, in <module>
    from .api import slack_message
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django_slack/api.py", line 10, in <module>
    backend = from_dotted_path(app_settings.BACKEND)()
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django_slack/utils.py", line 16, in from_dotted_path
    return getattr(__import__(module, {}, {}, (attr,)), attr)
  File "/home/ttn-dev/.venv/lib/python3.4/site-packages/django_slack/backends.py", line 27
    print "I: Slack message:"
                            ^
SyntaxError: Missing parentheses in call to 'print'
```

Looks like there's some problems with Python 3 support?

**Comment by lamby** [comment]
> problems with Python 3 support

What Python 3 support? :p

**Comment by lamby** [comment]
Okay, try 4.1.1 on PyPI :)

**Comment by lamby** [comment]
Actually this might be deeper - I forgot there was an outstanding PR for this https://github.com/lamby/django-slack/pull/12
