### ISSUE TITLE
Error when trying to log DisallowedHost error

### ISSUE THREAD

**Issue by joshblum** [lamby/django-slack#40]
I'm trying to log `DisallowedHost` errors to slack with the following logging config:
```
[...]
    'handlers': {
        'slack': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django_slack.log.SlackExceptionHandler',
        },
     },
     'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['slack'],
            'propagate': False,
           'level': 'ERROR',
        },
}
[...]
```
The problem is that when trying to get the error traceback, the same exception is raised (`django.core.exceptions.DisallowedHost`)

```
[...]
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/virtualenv/lib/python3.4/site-packages/whitenoise/base.py", line 119, in __call__
    return self.application(environ, start_response)
  File "/virtualenv/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 204, in get_response
    'request': request
  File "/usr/lib/python3.4/logging/__init__.py", line 1303, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
    self.handle(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
    self.emit(record)
  File "/virtualenv/lib/python3.4/site-packages/django_slack/log.py", line 53, in emit
    reporter.get_traceback_text(),
  File "/virtualenv/lib/python3.4/site-packages/django/views/debug.py", line 390, in get_traceback_text
    return t.render(c)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 647, in resolve
    obj = self.var.resolve(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "/virtualenv/lib/python3.4/site-packages/django/template/base.py", line 847, in _resolve_lookup
    current = current()
  File "/virtualenv/lib/python3.4/site-packages/django/http/request.py", line 151, in build_absolute_uri
    host=self.get_host(),
  File "/virtualenv/lib/python3.4/site-packages/django/http/request.py", line 101, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header
```

Any ideas how to avoid raising this when trying to log the error?

**Comment by lamby** [comment]
Avoiding it entirely, no... or at least it seems more of a flaw in Django.

We should probably wrap the ``reporter.get_traceback_text()`` though. (Closing issue with that commit)

**Comment by joshblum** [comment]
I commented on the commit, i think we should reopen this for a better fix. Happy to help if you want I'll submit a PR

**Comment by joshblum** [comment]
Also, thanks for being so responsive with this and the other PR, much appreciated :)

**Comment by lamby** [comment]
(For posterity, there is more discussion here: https://github.com/lamby/django-slack/commit/ac2e7b6577245c6ced56810f90ef3f86667df955#commitcomment-16574573)

**Comment by joshblum** [comment]
Thanks so much for helping! 

Is there a reason we don't try a best effort to give more information if the `get_traceback_text` call fails? Is there useful information in the `exc_info` object?

**Comment by blueyed** [comment]
Just for reference: I've filed a bug with Django: https://code.djangoproject.com/ticket/27506.
