### ISSUE TITLE
EncodeError with CeleryBackend using Python 3.5

### ISSUE THREAD

**Issue by woutor** [lamby/django-slack#53]
Hi, 

I get the following error using the CeleryBackend on Python 3.5:

```Traceback:
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in wrapper
  618.                 return self.admin_site.admin_view(view)(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/sites.py" in inner
  233.             return view(request, *args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in change_view
  1521.         return self.changeform_view(request, object_id, form_url, extra_context)
File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper
  34.             return bound_func(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func
  30.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/usr/local/lib/python3.5/contextlib.py" in inner
  30.                 return func(*args, **kwds)
File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in changeform_view
  1469.                 self.save_model(request, new_object, form, not add)
File "/app/hq/admin/event.py" in save_model
  58.             'change': change,
File "/usr/local/lib/python3.5/site-packages/django_slack/api.py" in slack_message
  114.         backend.send(endpoint_url, data, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django_slack/backends.py" in send
  65.         self._send.delay(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/celery/app/task.py" in delay
  453.         return self.apply_async(args, kwargs)
File "/usr/local/lib/python3.5/site-packages/celery/app/task.py" in apply_async
  565.             **dict(self._get_exec_options(), **options)
File "/usr/local/lib/python3.5/site-packages/celery/app/base.py" in send_task
  354.                 reply_to=reply_to or self.oid, **options
File "/usr/local/lib/python3.5/site-packages/celery/app/amqp.py" in publish_task
  310.             **kwargs
File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py" in publish
  165.             compression, headers)
File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py" in _prepare
  241.              body) = dumps(body, serializer=serializer)
File "/usr/local/lib/python3.5/site-packages/kombu/serialization.py" in dumps
  164.             payload = encoder(data)
File "/usr/local/lib/python3.5/contextlib.py" in __exit__
  77.                 self.gen.throw(type, value, traceback)
File "/usr/local/lib/python3.5/site-packages/kombu/serialization.py" in _reraise_errors
  59.         reraise(wrapper, wrapper(exc), sys.exc_info()[2])
File "/usr/local/lib/python3.5/site-packages/kombu/five.py" in reraise
  131.             raise value.with_traceback(tb)
File "/usr/local/lib/python3.5/site-packages/kombu/serialization.py" in _reraise_errors
  55.         yield
File "/usr/local/lib/python3.5/site-packages/kombu/serialization.py" in dumps
  164.             payload = encoder(data)
File "/usr/local/lib/python3.5/site-packages/anyjson/__init__.py" in dumps
  141.         return implementation.dumps(value)
File "/usr/local/lib/python3.5/site-packages/anyjson/__init__.py" in dumps
  89.             raise TypeError(TypeError(*exc.args)).with_traceback(sys.exc_info()[2])
File "/usr/local/lib/python3.5/site-packages/anyjson/__init__.py" in dumps
  87.             return self._encode(data)
File "/usr/local/lib/python3.5/json/__init__.py" in dumps
  230.         return _default_encoder.encode(obj)
File "/usr/local/lib/python3.5/json/encoder.py" in encode
  198.         chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.5/json/encoder.py" in iterencode
  256.         return _iterencode(o, 0)
File "/usr/local/lib/python3.5/json/encoder.py" in default
  179.         raise TypeError(repr(o) + " is not JSON serializable")

Exception Type: EncodeError at /core/event/1/
Exception Value: b'Hello world' is not JSON serializable
```

Apparently, the template contents are returned as a Bytes literal instead of a string: 
```
self._send.delay(*args, **kwargs):
	
('https://slack.com/api/chat.postMessage',
 {'channel': '#general',
  'text': b'Hello world',
  'token': 'xoxp-xxx',
  'username': 'xxx'})
```

Any idea?

**Comment by lamby** [comment]
Could you try replacing the ``encode`` on line 66 with ``decode``. That should give us a ``str`` type in PY3 and PY2.

**Comment by aleccool213** [comment]
I am getting an error with this on Python 3.5. 

```
016-08-03T22:47:35.511158+00:00 app[worker.1]: [2016-08-03 17:47:35,509: ERROR/MainProcess] Task fizz.bizz.tasks.send_provider_post_slack_message[1c3ce59c-7d08-4e55-ac83-f552e226721c] raised unexpected: TypeError("b'PROVIDER  has been created, please review submission and provide update to provider in 2 business days.' is not JSON serializable",)
2016-08-03T22:47:35.511176+00:00 app[worker.1]: Traceback (most recent call last):
2016-08-03T22:47:35.511177+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
2016-08-03T22:47:35.511178+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)
2016-08-03T22:47:35.511179+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
2016-08-03T22:47:35.511179+00:00 app[worker.1]:     return self.run(*args, **kwargs)
2016-08-03T22:47:35.511180+00:00 app[worker.1]:   File "/app/fizz/bizz/tasks.py", line 20, in send_provider_post_slack_message
2016-08-03T22:47:35.511181+00:00 app[worker.1]:     'provider_name': provider,
2016-08-03T22:47:35.511182+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django_slack/api.py", line 111, in slack_message
2016-08-03T22:47:35.511182+00:00 app[worker.1]:     data = {'payload': json.dumps(data)}
2016-08-03T22:47:35.511183+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/json/__init__.py", line 230, in dumps
2016-08-03T22:47:35.511184+00:00 app[worker.1]:     return _default_encoder.encode(obj)
2016-08-03T22:47:35.511184+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/json/encoder.py", line 199, in encode
2016-08-03T22:47:35.511184+00:00 app[worker.1]:     chunks = self.iterencode(o, _one_shot=True)
2016-08-03T22:47:35.511185+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/json/encoder.py", line 257, in iterencode
2016-08-03T22:47:35.511186+00:00 app[worker.1]:     return _iterencode(o, 0)
2016-08-03T22:47:35.511189+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/json/encoder.py", line 180, in default
2016-08-03T22:47:35.511189+00:00 app[worker.1]:     raise TypeError(repr(o) + " is not JSON serializable")
2016-08-03T22:47:35.511190+00:00 app[worker.1]: TypeError: b'PROVIDER  has been created, please review submission and provide update to provider in 2 business days.' is not JSON serializable
```

**Comment by lamby** [comment]
@aleccool213 It's unclear whether you are seeing this with my patch or not. Please clarify.

**Comment by aleccool213** [comment]
@lamby Sorry this is without the patch you mentioned above. I am using Celery but not passed in as a config var into django-slack itself. Just wanted to give more context to this issue.

**Comment by lamby** [comment]
@aleccool213 No problem. Could you try the patch..?

**Comment by aleccool213** [comment]
@lamby Tried the patch and got an error saying `decode cant work on str type`. Hmm, this seems suspected by reading on what `decode` is suppose to do.

I am assuming the return value of `render_to_string` needs to be encoded in utf8? Your suggestion goes against that though? I am unfamiliar with how `api.py` works right now :/

**Comment by lamby** [comment]
> I am assuming the return value of render_to_string needs to be encoded in utf8

Right, but is it not already? https://github.com/lamby/django-slack/blob/master/django_slack/api.py#L66  :p

**Comment by aleccool213** [comment]
@lamby yeh, but your patch suggests to change that :S Just slightly confused.
